version: "3.8"

services:
  medusa-backend:
    build: .
    container_name: medusa-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=9000
      - DATABASE_URL=postgres://tehergumiadmin:rdvl53oxgoGEWXx4AO03npRxBTfPHBpjAlyGrLzWuhGHbPaZYsFnfmPlDN5c0iJC@172.20.0.15:5432/tehergumi
      - REDIS_URL=redis://default:zvMezVxP4HKFwtsSuC5TwqT2k99Yl8OCGdmqcs1hDNGRbMrFAPU9UEsjv5u2co30@kssos0cscgcc88wco80soc0g:6379/0
      - JWT_SECRET=your-secret
      - COOKIE_SECRET=your-cookie-secret
      - MEDUSA_ADMIN_CORS=https://admin.teherguminet.hu
      - MEDUSA_STORE_CORS=https://teherguminet.hu,https://www.teherguminet.hu
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.services.medusa.loadbalancer.server.port=9000"
      - "traefik.http.routers.medusa.rule=Host(`admin.teherguminet.hu`)"
      - "traefik.http.routers.medusa.entrypoints=https"
      - "traefik.http.routers.medusa.tls=true"
      - "traefik.http.routers.medusa.tls.certresolver=letsencrypt"

networks:
  coolify:
    external: true
